# Introduzione a Numpy
**Autore:** Prof. Corrado Caudek\
**Licenza:** [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/)  
**Modificato da:** Luca Pugnetti\
**Link alla documentazione:** [NumPy](https://numpy.org/doc/stable/)

Anche se la Standard Library di Python offre molte funzioni utili per l'analisi dei dati, è conveniente utilizzare varie funzioni specifiche contenute in altri moduli. I moduli più utili per l'analisi dei dati sono:

- NumPy per i calcoli numerici,
- Pandas per caricare e manipolare i dati,
- Matplotlib e Seaborn per visualizzare i dati.

In questo capitolo introdurremo NumPy. NumPy è l'abbreviazione di Numerical Python: un'estensione del linguaggio pensata per il calcolo algebrico e matriciale. Numpy consente di lavorare con vettori e matrici in maniera più efficiente e veloce di quanto non si possa fare con le liste e le liste di liste (matrici) di Python. Inoltre, Numpy aggiunge una serie di funzioni matematiche di base e la possibilità di generare numeri casuali.

## Gli array nel modulo NumPy

In Python puro abbiamo a disposizione oggetti numerici (interi e a virgola mobile) e contenitori (liste, dizionari e insiemi). Numpy fornisce un nuovo tipo di dato: un array N-dimensionale (`ndarray`). Il costrutto `ndarray` è  un oggetto di tipo array multidimensionale caratterizzato da alcune proprietà, come:

- *dimensioni*: gli `ndarray` possono avere da una a un numero arbitrario di dimensioni, che vengono definite come "assi". Ad esempio, un array può essere unidimensionale (un vettore), bidimensionale (una matrice), tridimensionale (un cubo), e così via;
- *tipo di dato*: tutti gli elementi di un `ndarray` devono avere lo stesso tipo di dato, che può essere ad esempio float, int, bool o string (questo li differenzia dalle liste in puro Python, che non sono omogenee);
- *forma*: la forma di un `ndarray` indica le dimensioni dell'array, cioè il numero di elementi per ogni asse. Ad esempio, un array con forma (3, 4) ha 3 righe e 4 colonne;
- *indicizzazione*: gli `ndarray` possono essere indicizzati come gli array Python standard, ma consentono anche indicizzazioni più avanzate.

Gli `ndarray` offrono una vasta gamma di funzioni e metodi per manipolare e analizzare i dati in essi contenuti, tra cui operazioni matematiche, statistiche, trasformazioni e manipolazioni di dati.

**Terminologia**

- Con *size* di un array intendiamo il numero di elementi presenti in un array;
- Con *rank* di un array si intende il numero di assi/dimensioni di un array;
- Con *shape* di un array intendiamo le dimensioni dell'array, cioè una tupla di interi
contenente il numero di elementi per ogni dimensione.

<center>
    <img src="https://ccaudek.github.io/ds4psy_2023/_images/size_rank_shape.png" height="300px">
</center>



<br>

**Creare `ndarray`**

Il modo più semplice per creare un `ndarray` è quello di convertire una lista Python. Per esempio, possiamo creare un array 1-D nel modo seguente:

In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

L'istruzione precedente ha creato un vettore, chiamato `a`, con 6 elementi che sono i numeri interi indicati in parentesi quadra:

In [3]:
a

array([1, 2, 3, 4, 5, 6])

**Indicizzazione**

Se voglio estrarre un singolo elemento del vettore lo indicizzo con la sua posizione (si ricordi che l'indice inizia da 0):

In [4]:
a[0]

np.int64(1)

In [5]:
a[2]

np.int64(3)

Un array 2-D si crea nel modo seguente:

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Estraggo un singolo elemento dall'array:

In [7]:
print(a[0, 2])

3


Estraggo una riga dall'array:

In [8]:
print(a[1])

[5 6 7 8]


Estraggo una colonna dall'array:

In [9]:
print(a[:, 1])

[ 2  6 10]


Estraggo una sotto-matrice dall'array:

In [10]:
print(a[:2, 1:3])

[[2 3]
 [6 7]]


In [11]:
print(a[:1, 1:3])

[[2 3]]


### Funzioni per `ndarray`

Numpy offre varie funzioni per creare `ndarray`. Per esempio, è possibile creare un array 1-D con la funzione `.arange(start, stop, incr, dtype=..)` che fornisce l'intervallo di numeri compreso fra `start`, `stop`, al passo `incr`:

In [12]:
b = np.arange(2, 9, 2)
b

array([2, 4, 6, 8])

Si usa spesso `.arange` per creare sequenze a incrementi unitari:

In [13]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Un'altra funzione molto utile è `.linspace`:

In [14]:
(10-0)/19

0.5263157894736842

In [15]:
x = np.linspace(0, 10, num=20, endpoint=False)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
x = np.linspace(0, 10, num=20)
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

Fissati gli estremi (qui 0, 10) e il numero di elementi desiderati, `.linspace` determina in maniera automatica l'incremento.

Una proprietà molto utile dei `ndarray` è la possibilità di filtrare gli elementi di un array che rispondono come `True` ad un criterio. Per esempio:

In [17]:
x[x > 7]

array([ 7.36842105,  7.89473684,  8.42105263,  8.94736842,  9.47368421,
       10.        ])

perché solo gli ultimi sei elementi di `x` rispondono `True` al criterio $x > 7$.

Le dimensioni ("assi") di un `ndarray` vengono ritornate dal metodo `.ndim`. Per esempio:

In [ ]:
a.ndim

2

Il numero di elementi per ciascun asse viene ritornato dal metodo `.shape`:

In [ ]:
a.shape

(3, 4)

## Operazioni sugli array

Numpy è uno strumento molto utile per eseguire operazioni algebriche sugli elementi degli array. Spesso, ci limiteremo ad utilizzare array che rappresentano vettori (ovvero array di rank 1), in cui gli elementi del vettore possono rappresentare, ad esempio, le misure ottenute su una qualche variabile. Utilizzando Numpy, siamo in grado di automatizzare le comuni operazioni aritmetiche che normalmente svolgiamo su coppie di numeri, ma applicandole a tutti gli elementi dell'array. Questo permette di lavorare in modo molto efficiente con grandi quantità di dati e di effettuare analisi su di essi con facilità.

Supponiamo, ad esempio, di volere calcolare l'indice BMI:

$$
BMI = \frac{kg}{m^2}.
$$

Supponiamo inoltre di avere raccolto i dati di 4 individui:

In [ ]:
m = np.array([1.62, 1.75, 1.55, 1.74])
kg = np.array([55.4, 73.6, 57.1, 59.5])
m, kg

(array([1.62, 1.75, 1.55, 1.74]), array([55.4, 73.6, 57.1, 59.5]))

dove `m` è l'array che contiene i dati relativi all'altezza in metri dei quattro individui e `kg` è l'array che contiene i dati relativi al peso in kg. I dati sono organizzati in modo tale che il primo elemento di entrambi i vettori si riferisce alle misure del primo individuo, il secondo elemento dei due vettori si riferisce alle misure del secondo individuo, ecc. Per il primo individuo del campione, l'indice di massa corporea è

In [ ]:
55.4 / 1.62**2

21.109586953208346

Si noti che non abbiamo bisogno di scrivere `55.4 / (1.62**2)` in quanto, in Python, l'elevazione a potenza viene eseguita prima della somma e della divisione (come in tutti i linguaggi). Usando i dati immagazzinati nei due vettori, lo stesso risultato si ottiene nel modo seguente:

In [ ]:
kg[0] / m[0]**2

np.float64(21.109586953208346)

Se ora non specifichiamo l'indice (per esempio, `[0]`), le operazioni aritmetiche indicate verranno eseguite *per ciascuna coppia* di elementi corrispondenti nei due vettori:

In [ ]:
bmi = kg / m**2

Otteniamo così, con una sola istruzione, l'indice BMI dei quattro individui:

In [ ]:
bmi.round(1)

array([21.1, 24. , 23.8, 19.7])

Questo esempio mostra come le normali operazioni aritmetiche vengano applicate sugli array *elemento per elemento*.

## Broadcasting

Il broadcasting è un meccanismo che consente a Numpy di eseguire operazioni tra array di diverse dimensioni o tra un array e uno scalare, anche quando le dimensioni non sono compatibili tra loro. In questo modo, Numpy può estendere automaticamente la dimensione di uno degli operandi in modo da rendere possibile l'operazione.

Ad esempio, è possibile effettuare un'operazione tra un array e un singolo numero (operazione tra un vettore e uno scalare), oppure tra array di due dimensioni diverse, senza dover esplicitamente allineare le dimensioni degli array. In questi casi, Numpy utilizza il *broadcasting* per allineare le dimensioni degli array in modo da eseguire l'operazione richiesta. Questo rende il codice più compatto e leggibile, e consente di evitare il lavoro manuale di espansione degli array.

In sintesi, il *broadcasting* è un meccanismo molto utile in Numpy che consente di eseguire operazioni tra array di diverse dimensioni o tra un array e uno scalare in modo automatico, senza dover esplicitamente allineare le dimensioni degli array.

Ad esempio

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

## Altre operazioni sugli array

C'è un numero enorme di funzioni predefinite in NumPy che calcolano automaticamente diverse quantità sui `ndarray`. Ad esempio:

- `mean()`: calcola la media di un vettore o matrice;
- `sum()`: calcola la somma di un vettore o matrice;
- `std()`: calcola la deviazione standard;
- `min()`: trova il minimo nel vettore o matrice;
- `max()`: trova il massimo;
- `ndim`: dimensione del vettore o matrice;
- `shape`: restituisce una tupla con la "forma" del vettore o matrice;
- `size`: restituisce la dimensione totale del vettore (=ndim) o della matrice;
- `dtype`: scrive il tipo numpy del dato;
- `zeros(num)`: scrive un vettore di num elementi inizializzati a zero;
- `arange(start,stop,step)`: genera un intervallo di valori (interi o reali, a seconda dei valori di start, ecc.) intervallati di step. Nota che i dati vengono generati nell'intervallo aperto [start,stop)!
- `linstep(start,stop,num)`: genera un intervallo di num valori interi o reali a partire da start fino a stop (incluso!);
- `astype(tipo)`: converte l'ndarray nel tipo specificato

Per esempio:

In [ ]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
[x.min(), x.max(), x.sum(), x.mean(), x.std()]

[np.int64(1),
 np.int64(3),
 np.int64(6),
 np.float64(2.0),
 np.float64(0.816496580927726)]

## Lavorare con formule matematiche

L'implementazione delle formule matematiche sugli array è un processo molto semplice con Numpy. Possiamo prendere ad esempio la formula della deviazione standard che discuteremo nel capitolo {ref}`loc-scale-notebook`:

$$
s = \sqrt{\sum_{i=1}^n\frac{(x_i - \bar{x})^2}{n}}
$$

L'implementazione su un array NumPy è la seguente:

In [ ]:
np.sqrt(np.sum((x - np.mean(x)) ** 2) / np.size(x))

np.float64(0.816496580927726)

Questa implementazione funziona nello stesso modo sia che `x` contenga 3 elementi (come nel caso presente) sia che `x` contenga migliaia di elementi. È importante notare l'utilizzo delle parentesi tonde per specificare l'ordine di esecuzione delle operazioni. In particolare, nel codice fornito, si inizia calcolando la media degli elementi del vettore `x` per mezzo della funzione `np.mean(x)`. Questa operazione produce uno scalare, ovvero un singolo valore numerico che rappresenta la media degli elementi del vettore. L'utilizzo delle parentesi tonde è fondamentale per garantire l'ordine corretto delle operazioni. In questo caso, la funzione `np.mean()` viene applicata al vettore `x` prima di qualsiasi altra operazione matematica. Senza le parentesi tonde, le operazioni verrebbero eseguite in un ordine diverso e il risultato potrebbe essere errato.

In [ ]:
np.mean(x)

np.float64(2.0)

Successivamente, eseguiamo la sottrazione dei singoli elementi del vettore `x` per la media del vettore stesso, ovvero $x_i - \bar{x}$, utilizzando il meccanismo del broadcasting.

In [ ]:
x - np.mean(x)

array([-1.,  0.,  1.])

Eleviamo poi al quadrato gli elementi del vettore che abbiamo ottenuto:

In [ ]:
(x - np.mean(x)) ** 2

array([1., 0., 1.])

Sommiamo gli elementi del vettore:

In [ ]:
np.sum((x - np.mean(x)) ** 2)

np.float64(2.0)

Dividiamo il numero ottenuto per $n$. Questa è la varianza di $x$:

In [ ]:
res = np.sum((x - np.mean(x)) ** 2) / np.size(x)
res

np.float64(0.6666666666666666)

Infine, per ottenere la deviazione standard, prendiamo la radice quadrata:

In [ ]:
np.sqrt(res)

np.float64(0.816496580927726)

Il risultato ottenuto coincide con quello che si trova applicando la funzione `np.std()`:

In [ ]:
np.std(x)

np.float64(0.816496580927726)

## Slicing

Per concludere, spendiamo ancora alcune parole sull'indicizzazione degli `ndarray`.

Slicing in Numpy è un meccanismo che consente di selezionare una porzione di un array multidimensionale, ovvero una sotto-matrice o un sotto-vettore. Per selezionare una porzione di un array, si utilizza la sintassi `[start:stop:step]`, dove `start` indica l'indice di partenza della porzione, `stop` indica l'indice di fine e `step` indica il passo da utilizzare per la selezione. Se uno o più di questi valori vengono omessi, vengono utilizzati dei valori di default.

Ad esempio, se abbiamo un array `arr` di dimensione (3, 4) e vogliamo selezionare la seconda colonna, possiamo usare la sintassi  `arr[:, 1]`. In questo caso, il simbolo `:` indica che vogliamo selezionare tutte le righe, mentre il numero `1` indica che vogliamo selezionare la seconda colonna.

Inoltre, possiamo utilizzare il meccanismo di slicing anche per selezionare porzioni di array multidimensionali. Ad esempio, se abbiamo un array `arr` di dimensione (3, 4, 5) e vogliamo selezionare la prima riga di ciascuna matrice 4x5, possiamo usare la sintassi `arr[:, 0, :]`.

Per esempio, creiamo l'array `a`  di rank 2 con shape (3, 4):

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Utilizziamo il meccanismo di slicing per estrarre la sottomatrice composta dalle prime 2 righe e dalle colonne 1 e 2. `b` è l'array risultante di dimensione (2, 2):

In [ ]:
b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

È importante sapere che uno slice di un array in Numpy è una vista degli stessi dati, il che significa che modificarlo implica la modifica dell'array originale. In pratica, quando si modifica uno slice di un array, si sta modificando direttamente l'array originale e tutte le altre visualizzazioni dell'array vedranno la stessa modifica. Questo avviene perché Numpy è progettato per gestire enormi quantità di dati, pertanto cerca di evitare il più possibile di effettuare copie dei dati.

Questo comportamento deve essere preso in considerazione durante la modifica degli array in Numpy, al fine di evitare modifiche accidentali o indesiderate. In alcuni casi, è possibile utilizzare il metodo `copy()` per creare una copia indipendente di un array e lavorare sulla copia senza modificare l'originale. Vediamo un esempio.

In [ ]:
print(a[0, 1])


2


In [ ]:
b[0, 0] = 77


In [ ]:
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
c = a.copy()
c

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c[0, 1] = 33
c

array([[ 1, 33,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Alcuni esercizi

**Esercizio 1.** Creare un vettore nullo di dimensione 10 ma con il quinto valore che è 1.

In [ ]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Esercizio 2.** Creare un vettore con valori compresi tra 10 e 49.

In [ ]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Esercizio 3.** Invertire un vettore (il primo elemento diventa l'ultimo).

In [ ]:
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


**Esercizio 4.** Trovare gli indici degli elementi non zero di [1, 2, 0, 0, 4, 0].

In [ ]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


**Esercizio 5.** Crearere un array 10x10 con valori casuali e trovare i valori minimo e massimo.

In [ ]:
z = np.random.random((10,10))
z

array([[0.50614992, 0.68010509, 0.56927583, 0.9154881 , 0.82598071,
        0.97532742, 0.90271522, 0.20308724, 0.55411712, 0.49324423],
       [0.6979413 , 0.92996991, 0.92605314, 0.28821843, 0.77647511,
        0.7058558 , 0.73448111, 0.93795544, 0.80992597, 0.27197049],
       [0.03000261, 0.58144526, 0.59747072, 0.42511928, 0.79552807,
        0.71111223, 0.79676559, 0.39416173, 0.67576706, 0.25538655],
       [0.26038027, 0.42282722, 0.44439713, 0.28965789, 0.95648646,
        0.74295423, 0.8235214 , 0.44981978, 0.79176906, 0.08626614],
       [0.71459456, 0.8483471 , 0.70038425, 0.68977279, 0.88907506,
        0.21448304, 0.99302854, 0.65080157, 0.39600203, 0.07885811],
       [0.32862198, 0.67382871, 0.11875374, 0.13652161, 0.42375351,
        0.1843891 , 0.74261599, 0.32861542, 0.71578416, 0.20801154],
       [0.37306168, 0.22647597, 0.3230861 , 0.26030067, 0.23586606,
        0.66917457, 0.55131379, 0.71802477, 0.55482441, 0.73056015],
       [0.79991154, 0.45085369, 0.1941849

In [ ]:
z_min, z_max = z.min(), z.max()
print(z_min, z_max)

0.005145338931864196 0.9930285363024041


**Esercizio 6.** Creare un vettore casuale di dimensione 30 e trovare il valore medio.

In [ ]:
z = np.random.random(30)
z

array([0.43469555, 0.28147   , 0.80391131, 0.02676286, 0.17799902,
       0.96502583, 0.70308668, 0.96118021, 0.48484933, 0.29267571,
       0.75954826, 0.89031899, 0.51685968, 0.35655868, 0.40532054,
       0.40336097, 0.84615744, 0.37056519, 0.92332702, 0.98460037,
       0.91581024, 0.06940096, 0.91324625, 0.17576687, 0.99171036,
       0.16296016, 0.05226424, 0.21837074, 0.43160179, 0.74327871])

In [ ]:
m = z.mean()
print(m)

0.5420894655280079


**Esercizio 7.** Dato un array 1D, negare tutti gli elementi compresi tra 3 e 8, inplace.

In [ ]:
z = np.arange(11)
z[(z>3) & (z<8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


Qual è l'output di `print(sum(range(5),-1))`?

In [ ]:
print(sum(range(5),-1))

9


In [ ]:
range(5)

range(0, 5)

In [ ]:
sum(range(5))

10

**Esercizio 8.** Creare un vettore casuale di dimensione 10 e sostituire il valore massimo con 0.

In [ ]:
z = np.random.random(10)
z

array([0.6669764 , 0.0600586 , 0.18270532, 0.34456278, 0.93278718,
       0.78738941, 0.74792336, 0.62781023, 0.46697894, 0.93466505])

In [ ]:
z[z.argmax()] = 0
print(z)

[0.6669764  0.0600586  0.18270532 0.34456278 0.93278718 0.78738941
 0.74792336 0.62781023 0.46697894 0.        ]


**Esercizio 9.** Trovare il valore più vicino (a uno scalare dato) in un vettore.

In [ ]:
z = np.arange(100)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
v = np.random.uniform(0, 100)
v

3.3623273242963103

In [ ]:
index = (np.abs(z - v)).argmin()
print(z[index])

3


**Esercizio 10.** Convertire tutti gli elementi di un array numpy da float a integer.

In [ ]:
a = np.array([[2.5, 3.8, 1.5], [4.7, 2.9, 1.56]])
i = a.astype("int")

print(i)

[[2 3 1]
 [4 2 1]]


**Esercizio 11.** Convertire un array numpy binario (contenente solo 0 e 1) in un array numpy booleano.

In [ ]:
a = np.array([[1, 0, 0], [1, 1, 1], [0, 0, 0]])
b = a.astype("bool")

print(b)

[[ True False False]
 [ True  True  True]
 [False False False]]


**Esercizio 12.** Unire orizzontalmente due array numpy aventi la stessa prima dimensione (cioè lo stesso numero di righe negli array 2D).

In [ ]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

h = np.hstack((a1, a2))
print(h)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
v = np.vstack((a1, a2))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


**Esercizio 13.** Dati due array numpy, estrarre gli indici in cui gli elementi nei due array corrispondono.

**Esercizio 14.** Generare un array ripetendo un array più piccolo di 2 dimensioni 10 volte.

**Esercizio 15.** Generare un array 5x5 di interi casuali compresi tra 0 (incluso) e 10 (escluso).

**Esercizio 16.** Verificare se uno qualsiasi degli elementi di un array dato è diverso da zero.

**Esercizio 17.** Creare un confronto elemento per elemento (uguale, uguale entro una tolleranza) di due array dati.

**Esercizio 18.** Trovare i dati mancanti in un array dato.

**Esercizio 19.** Scrivi un programma NumPy per estrarre tutti i numeri da un array dato che sono inferiori e superiori ad un numero specificato.

**Esercizio 20.** Sostituire tutti i numeri in un array dato che sono uguali, minori e maggiori di un dato numero.

**Esercizio 21.** Moltiplicare due array dati della stessa dimensione elemento per elemento.